# Generated by Django 4.0.4 on 2022-07-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appjugadores', '0002_estadisticas_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='jugador',
            field=models.CharField(default='', max_length=50),
        ),
    ]
